#!/usr/bin/env bun

import { parseArgs } from 'node:util'

/**
 * Proxy helper for zsh:
 *
 * - setProxy: 生成 export + git config 的 shell 片段
 * - unsetProxy: 生成 unset + git config 清理的 shell 片段
 *
 * 设计用法（在 zsh 里）：
 *
 *   # 设置代理（保持现有命令名）
 *   setProxy() {
 *     eval "$(~/.zsh/functions/bun/proxy.ts set "$@")"
 *   }
 *
 *   unsetProxy() {
 *     eval "$(~/.zsh/functions/bun/proxy.ts unset "$@")"
 *   }
 *
 * 注意：本脚本不会直接修改当前 shell 环境，而是输出 shell 语句。
 */

type ProxyCommand = 'set' | 'unset'

interface SetProxyOptions {
  url: string
  port: number
  noProxy: string
}

function isPort(value: string): boolean {
  return /^[0-9]+$/.test(value)
}

function isUrl(value: string): boolean {
  return value.includes('://')
}

function parseSetArgs(args: string[]): SetProxyOptions {
  const {
    values,
    positionals,
  } = parseArgs({
    args,
    options: {
      'port': {
        type: 'string',
        short: 'p',
      },
      'url': {
        type: 'string',
        short: 'u',
      },
      'no-proxy': {
        type: 'string',
        short: 'n',
      },
    },
    allowPositionals: true,
  })

  let url
    = typeof values.url === 'string' && values.url.length > 0
      ? values.url
      : 'http://127.0.0.1'

  let port: number
  if (typeof values.port === 'string') {
    if (!isPort(values.port)) {
      throw new Error(`端口参数错误: ${values.port}`)
    }
    port = Number(values.port)
  }
  else {
    port = 7890
  }

  const noProxy
    = typeof values['no-proxy'] === 'string' && values['no-proxy'].length > 0
      ? values['no-proxy']
      : 'localhost,127.0.0.1,::1,192.168.0.0/16,10.0.0.0/8'

  for (const arg of positionals) {
    if (isPort(arg)) {
      port = Number(arg)
    }
    else if (isUrl(arg)) {
      url = arg
    }
    else {
      throw new Error(
        `未知参数: ${arg}\n`
        + '用法: setProxy [URL] [端口] | setProxy [-p|--port <端口>] [-u|--url <URL>] [-n|--no-proxy <排除列表>]\n'
        + '示例: setProxy 8080 | setProxy -p 8080 | setProxy --url http://proxy.example.com',
      )
    }
  }

  return { url, port, noProxy }
}

function buildSetProxyShell(opts: SetProxyOptions): string {
  const proxy = `${opts.url}:${opts.port}`
  const noProxy = opts.noProxy

  const lines = [
    `# generated by bun proxy.ts`,
    `echo "🔧 设置代理: ${proxy}"`,
    `echo "🚫 排除地址: ${noProxy}"`,
    `export http_proxy=${proxy}`,
    `export HTTP_PROXY=${proxy}`,
    `export https_proxy=${proxy}`,
    `export HTTPS_PROXY=${proxy}`,
    `export no_proxy=${noProxy}`,
    `export NO_PROXY=${noProxy}`,
    `git config --global http.proxy "${proxy}"`,
    `git config --global https.proxy "${proxy}"`,
    `echo "✅ 代理设置完成"`,
  ]

  return `${lines.join('\n')}\n`
}

function buildUnsetProxyShell(): string {
  const lines = [
    `# generated by bun proxy.ts`,
    `echo "🔧 清除代理..."`,
    `unset http_proxy HTTP_PROXY https_proxy HTTPS_PROXY no_proxy NO_PROXY`,
    `git config --global --unset http.proxy 2>/dev/null || true`,
    `git config --global --unset https.proxy 2>/dev/null || true`,
    `echo "✅ 代理已清除"`,
  ]
  return `${lines.join('\n')}\n`
}

function printUsage(): void {
  console.error(
    [
      '用法:',
      '  proxy.ts set   [options]  # 生成设置代理的 shell 片段',
      '  proxy.ts unset           # 生成清除代理的 shell 片段',
      '',
      '示例（在 zsh 中包一层函数）:',
      '  setProxy() { eval "$(~/.zsh/functions/bun/proxy.ts set "$@")" }',
      '  unsetProxy() { eval "$(~/.zsh/functions/bun/proxy.ts unset "$@")" }',
    ].join('\n'),
  )
}

async function main() {
  const [, , sub, ...rest] = process.argv

  if (!sub || sub === '-h' || sub === '--help') {
    printUsage()
    process.exit(sub
      ? 0
      : 1)
  }

  if (sub !== 'set' && sub !== 'unset') {
    console.error(`未知子命令: ${sub}`)
    printUsage()
    process.exit(1)
  }

  try {
    if (sub === 'set') {
      const opts = parseSetArgs(rest)
      process.stdout.write(buildSetProxyShell(opts))
    }
    else if (sub === 'unset') {
      process.stdout.write(buildUnsetProxyShell())
    }
    process.exit(0)
  }
  catch (err) {
    console.error((err as Error).message)
    process.exit(1)
  }
}

main()
